### ISSUE TITLE
Conflict with rpg mod

### ISSUE THREAD

**Issue by shallowdreamwu** [adainrivers/randomencounters#1]
Hello, brother，
When this mod is running at the same time as RPG, it will collapse once in a while，
Please have a look. Thank you for your production

**Comment by adainrivers** [comment]
Hello,

Do you have any more information about this. I'm running it with RPGMods on my personal server as well, but haven't had any crashes.

Thank you for your report.

**Comment by shallowdreamwu** [comment]
[VRisingServer.log](https://github.com/adainrivers/randomencounters/files/9139429/VRisingServer.log)
[stats_log.txt](https://github.com/adainrivers/randomencounters/files/9139430/stats_log.txt)
This is the log when the server crashed，Please, brother thank you

**Comment by adainrivers** [comment]
Thank you.

Do you also have the log file in the BepInEx folder when the server crashed?

**Comment by shallowdreamwu** [comment]
[logs.zip](https://github.com/adainrivers/randomencounters/files/9140234/logs.zip)
this？

**Comment by adainrivers** [comment]
![image](https://user-images.githubusercontent.com/93623214/179732677-9a4f6ae6-adf7-4336-95a4-7c9510f33cfd.png)

This one.

**Comment by shallowdreamwu** [comment]
[LogOutput.log](https://github.com/adainrivers/randomencounters/files/9140338/LogOutput.log)

**Comment by adainrivers** [comment]
Hi, 

This log doesn't have it.

I'll try to reproduce it on my server.

Thanks you.

**Comment by shallowdreamwu** [comment]
Thank you for helping me find brother

**Comment by adainrivers** [comment]
I've updated the mod, can you please test the new version and see if it's still happening?

**Comment by shallowdreamwu** [comment]
Now it has been tested for more than an hour without any problems. Thank you, brother. I'll give you feedback if there are any problems

**Comment by adainrivers** [comment]
That's great to hear. I'm closing this one. Please let me know if you have any other issues, or feedback. Enjoy!
